product added
eapg/restaurant pull request #5
Opened 2021-04-28 15:21 UTC by eapg

product name modified. new name product.py

2021-04-28 23:04 UTC, reynoldmorel requested changes

2021-04-28 23:04 UTC, reynoldmorel commented on scr/product.py
> +def __init__(self):
I think you need to add `class` keyword in python, in order to create class

2021-04-28 23:37 UTC, eapg commented on scr/product.py
> +def __init__(self):
done

2021-04-28 23:47 UTC, eapg commented on scr/product.py
> +def __init__(self):
done, was a mistake copying and pasting

2021-04-29 17:03 UTC, reynoldmorel approved these changes

2021-05-26 00:49 UTC, merged